### ISSUE TITLE
How to include class to my proyect

### ISSUE THREAD

**Issue by Juanperezc** [TomWright/ExtendedPDO#1]
some example of how to include the class in the project, sorry I am new to this

**Comment by TomWright** [comment]
Hi @Juanperezc,

The best way to use this in your project is by using [Composer](https://getcomposer.org/).
Here is an [introduction to composer](https://getcomposer.org/doc/00-intro.md).

Once you have it set up, simply require this package by running `composer require tomwright/extended-pdo` on the command line.
